Поправил формулировки в соответствии с нашими ценностями
kolesa-team/backend-department pull request #1
Opened 2023-05-10 14:43 UTC by WallEnd

Добавил описание зоны ответственности в каждом блоке

2023-05-11 03:24 UTC, antonsergeyev commented on grades.md
> +Junior - это следующий шаг на дорожной карте разработчика. Разработчик становится полноценным членом нашей команды, который отныне имеет чёткие полномочия и обязанности. Обычно зона отвественности Ju
ответственности
и перед "это" - тире

2023-05-11 03:24 UTC, antonsergeyev commented on grades.md
> +- Выделять часто используемые фрагменты кода в библиотеки
Выделение (т.к. соседние пункты - это существительные, а не глаголы)

2023-05-11 03:24 UTC, antonsergeyev commented on grades.md
> +- Знание и опыт применения подхода Domain Driven Design
не уверен что это реалистично, у нас большинство особо не в теме об этом (я в их числе).
а те, кто в теме, не спешат активно распространять знания

2023-05-11 03:24 UTC, antonsergeyev commented on grades.md
> +Senior - это ступень, подразумевающая очень высокий уровень технической экспертизы, ответственности и погружения в процессы бизнеса. Подразумевается что человек на этом уровне оказывает влияние своей
слово "подразумевается" повторяется дважды в соседних предложениях, предложил бы заменить на синоним - или вовсе его убрать, например так:
"Человек на этом уровне оказывает влияние своей экспертизой на всю компанию и весь технический департамент."

кстати, что означает весь технический департамент? должен ли сеньор бэкендер влиять на фронтенд и мобильную разработку?

2023-05-11 04:03 UTC, akimsir requested changes

2023-05-11 04:03 UTC, akimsir commented on grades.md
> +- Знание и опыт применения подхода Domain Driven Design
да опыта по этой теме можно долго не получать, так как в проектах уже сделано не по Domain Driven Design и применение его проблематично

2023-05-11 09:55 UTC, WallEnd commented on grades.md
> +Senior - это ступень, подразумевающая очень высокий уровень технической экспертизы, ответственности и погружения в процессы бизнеса. Подразумевается что человек на этом уровне оказывает влияние своей
`кстати, что означает весь технический департамент? должен ли сеньор бэкендер влиять на фронтенд и мобильную разработку?
`
Да, так и подразумевается, где-то человек влияет на работу тестирования, где-то на стандарты интерфейсов взаимодействия с фронтом или мобилкой. Иногда можно даже либу пильнуть под мобилку на гошечке (не лучший кейс но ради решения задачи бизнеса применимо)

2023-05-12 04:55 UTC, antonsergeyev commented on grades.md
> +Senior - это ступень, подразумевающая очень высокий уровень технической экспертизы, ответственности и погружения в процессы бизнеса. Подразумевается что человек на этом уровне оказывает влияние своей
понял
думаю можно было раскрыть это подробнее в самом документе.
если бы меня спросили про этот пункт, я бы не смог ответить также хорошо, как ты)

2023-05-12 04:55 UTC, antonsergeyev approved these changes

2023-05-12 09:03 UTC, alexandrwelcome commented
@WallEnd можешь плз мой акк добавить на ревью вот этот

2023-05-12 10:25 UTC, alexandrwelcome approved these changes

2023-05-12 10:55 UTC, lesmiras approved these changes

2023-05-12 11:11 UTC, akimsir approved these changes

2024-09-03 08:37 UTC, merged